src/src/Models/ErrorViewModel.cs
namespace src.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

src/src/Models/GetAllViewModel.cs
namespace src.Views.Valute;

public class GetAllViewModel
{
    public IEnumerable<KeyValuePair<string, Currency.DL.Valute>> Valutes { get; set; }
    public PageViewModel PageViewModel { get; set; }
}

src/src/Models/GetIndexModel.cs
namespace src.Models;

public class GetIndexModel
{
    public IEnumerable<KeyValuePair<string, Currency.DL.Valute>> Valutes { get; set; }
}

src/src/Models/PageViewModel.cs
namespace src.Views.Valute;

public class PageViewModel
{
    public int PageNumber { get; private set; }
    public int TotalPages { get; private set; }
 
    public PageViewModel(int count, int pageNumber, int pageSize)
    {
        PageNumber = pageNumber;
        TotalPages = (int)Math.Ceiling(count / (double)pageSize);
    }
 
    public bool HasPreviousPage
    {
        get
        {
            return (PageNumber > 1);
        }
    }
 
    public bool HasNextPage
    {
        get
        {
            return (PageNumber < TotalPages);
        }
    }
}

src/src/Controllers/ValuteController.cs
using Microsoft.AspNetCore.Mvc;
using Currency.BL;
using src.Models;
using src.Views.Valute;

namespace src.Controllers
{
    public class ValuteController : Controller
                {
                    private readonly IValuteService _service;

                    public ValuteController(IValuteService service)
                    {
                        _service = service;
                    }

                    public async Task<ActionResult> Index()
                    {
                        try
                        {
                            var allValute = await _service.GetAllAsync();
                            GetIndexModel getIndexModel = new GetIndexModel
                            {
                                Valutes = allValute
                            };
                            return View(getIndexModel);
                        }
                        catch(Exception e)
                        {
                            return ViewBag["Error"] = e.Message;
                        }

                    }

                    [HttpGet]           
                    public async Task<ActionResult> Get(string key)
                    {
                        if (string.IsNullOrWhiteSpace(key))
                        {
                            return ViewBag["Error"] = "Выбирите валюту из списка";
                        }
                        else
                        {
                            
                            var result = await _service.GetAsync(key);
                            return View(result);
                            
                        }
                    }
                    [HttpGet]
                    public async  Task<ActionResult> GetAll(int page = 1)
                    {
                        try
                        {
                            var size = 5;
                            var allValute = await _service.GetAllAsync();
                            var count = allValute.Count();
                            var items = allValute.Skip((page - 1) * size).Take(size);
                            PageViewModel pageViewModel = new PageViewModel(count, page, size);
                            GetAllViewModel viewModel = new GetAllViewModel
                            {
                                PageViewModel = pageViewModel,
                                Valutes = items
                            };
                            return View(viewModel);
                        }
                        catch(Exception e)
                        {
                            return ViewBag["Error"] = e.Message;
                        }
                    }
                }
}

src/src/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Курс валют</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/src.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Valute" asp-action="Index">Выбрать валюту</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Valute" asp-action="GetAll">Курс всех валют</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - src - <a asp-area="" asp-controller="Valute" asp-action="Index">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

src/src/Views/Valute/Get.cshtml
@model Currency.DL.Valute

@{
    ViewBag.Title = "Выбрать валюту";
    Layout = "_Layout";
}

<head></head>
<body>
<header><h2>@Model.CharCode</h2></header>
<main>
    <table class="table">
        <tr>
            <th>Название валюты</th><th>Цифровой код</th><th>Алфавитный код</th><th>Номинал</th>
            <th>Значение</th><th>Предыдущие значение</th>
        </tr>
        <tr>
            <td>@Model.Name</td><td>@Model.NumCode</td><td>@Model.CharCode</td><td>@Model.Nominal</td>
            <td>@Model.Value</td><td>@Model.Previous</td>
        </tr>
    </table>
</main>
<footer></footer>
</body>

src/src/Views/Valute/GetAll.cshtml
@model src.Views.Valute.GetAllViewModel

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<!DOCTYPE html>
<style>
         @@font-face {
             font-family: 'FontAwesome';
             src: url('https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/fonts/fontawesome-webfont.woff2') format('woff2'), 
             url('https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/fonts/fontawesome-webfont.woff') format('woff'), 
             url('https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/fonts/fontawesome-webfont.ttf') format('truetype');
             font-weight: normal;
             font-style: normal
         }
  
         .glyphicon {
             display: inline-block;
             font: normal normal normal 14px/1 FontAwesome;
             font-size: inherit;
             text-rendering: auto;
             -webkit-font-smoothing: antialiased;
             -moz-osx-font-smoothing: grayscale
         }
  
         .glyphicon-chevron-right:before {
             content: "\f054";
         }
  
         .glyphicon-chevron-left:before {
             content: "\f053";
         }
     </style>
<html xmlns="http://www.w3.org/1999/html">
<head>
    <title>Список валют</title>
</head>
<h1>Cписок валют</h1>
<body>
<div>
    <table class="table">
        <tr>
            <th>Название валюты</th><th>Цифровой код</th><th>Алфавитный код</th><th>Номинал</th>
            <th>Значение</th><th>Предыдущие значение</th>
        </tr>
        @foreach (var item in Model.Valutes)
        {
            <tr>
                <td>@item.Value.Name</td><td>@item.Value.NumCode</td><td>@item.Value.CharCode</td><td>@item.Value.Nominal</td>
                <td>@item.Value.Value</td><td>@item.Value.Previous</td>
            </tr>
        }
    </table>
</div>
@if (Model.PageViewModel.HasPreviousPage)
{
    <a asp-action="GetAll"
       asp-route-page="@(Model.PageViewModel.PageNumber - 1)"
       class="btn btn-outline-dark">
        <i class="glyphicon glyphicon-chevron-left"></i>
        Назад
    </a>
}
@if (Model.PageViewModel.HasNextPage)
{
    <a asp-action="GetAll"
       asp-route-page="@(Model.PageViewModel.PageNumber + 1)"
       class="btn btn-outline-dark">
        Вперед
        <i class="glyphicon glyphicon-chevron-right"></i>
    </a>
}
</body>
</html>

src/src/Views/Valute/Index.cshtml
@model GetIndexModel
@{
    ViewData["Title"] = "Курс валюты";
}

<head><h2>Список валют</h2></head>
<body>
<header></header>
<main><form asp-controller="Valute" asp-action="Get" method="Get">
          <select name="key">
              @foreach (var item in Model.Valutes)
              {
                  <option value="@item.Key">@item.Value.Name</option>
              }
          </select>
          <input type="submit" value="Искать" class="btn btn-primary"/>
      </form>
</main>
<footer>
</footer>
</body>